#!/bin/bash

if [ $# -lt 2 ]
then
    echo "Usage:" $(basename $0) "<pid> <targetfile>"
    exit
fi

perf record -F 99 -p $1 -g -o /tmp/perf.data -- sleep 60
perf script -i /tmp/perf.data > /tmp/out.perf
$FG_HOME/stackcollapse-perf.pl /tmp/out.perf > /tmp/out.folded
$FG_HOME/flamegraph.pl /tmp/out.folded > $2

