#!/bin/bash

# 从命令行获取文件夹路径
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <folder_path>"
    exit 1
fi

folder_path="$1"
cur_base=$(pwd)
video_base=/home/cookiepie/Videos
music_base=/home/cookiepie/Music

if [ $cur_base != $video_base ]
then
    echo "Script only works under $video_base"
    echo "Currently in $cur_base"
    exit
fi

# 遍历文件夹
find "$folder_path" -type f -name "*.webm" -print0 | while read -d $'\0' input_file_path; do
    # 构建输出文件路径，替换后缀为.mp3
    output_file_path="$music_base/${input_file_path%.webm}.mp3"
    escaped_output_file_path=$(echo "$output_file_path" | sed 's/\\/\\\\/g; s/ /\\ /g; s/"/\\"/g; s/'\''/\\'\''/g; s/(/\\(/g; s/)/\\)/g; s/{/\\{/g; s/}/\\}/g')
    escaped_input_file_path=$(echo "$input_file_path" | sed 's/\\/\\\\/g; s/ /\\ /g; s/"/\\"/g; s/'\''/\\'\''/g; s/(/\\(/g; s/)/\\)/g; s/{/\\{/g; s/}/\\}/g')
    mkdir -p "~/Music/$folder_path"

    echo "+FFMPEG ${input_file_path%.webm}"
    # 构建执行的ffmpeg命令
    ffmpeg_cmd="ffmpeg -i $escaped_input_file_path -map 0:a  -codec:a libmp3lame $escaped_output_file_path"
    eval $ffmpeg_cmd < /dev/null
done

